name: Update translation files
on:
  push:
    branches:
      - master


jobs:
 run:
   name: Update translation files
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Setup po4a
     run: |
       sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E77D14FE3C9A28E588A34E7469977F2B42813EC6
       sudo add-apt-repository ppa:pgquiles/uyuni
       sudo apt-get install -y make po4a

   - name: Update gettext files
     run: |
        git branch
        make pot

   - name: Commit changes
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_user_name: Galaxy CI
       commit_user_email: galaxy-ci@suse.de
       commit_author: Galaxy CI <galaxy-ci@suse.de>
       commit_message: 'Automatic commit: update translation files'
#       add: 'l10n-weblate'
       branch: master
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
